# Generated by Django 4.0 on 2022-01-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_product_slug'),
        ('accounts', '0003_remove_user_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to='shop.Product'),
        ),
    ]
